name: Peoples-newspaper

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 9:00 AM UTC 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖

      - name: Run newspaper downloader script
        run: python script_name.py  # 替换为你实际的 Python 脚本文件名

      - name: Commit and push PDF files to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add papers/
          git commit -m "Add merged PDFs for today's newspaper"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token 用于推送
